app:
  name: "Interview Test API"
  debug: false
  api_v1_str: "/api/v1"

server:
  host: "0.0.0.0"
  port: 8000
  reload: true

logging:
  level: "INFO"
  format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
  file: "api/logs/api.log"
  rotation: "500 MB"

cors:
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"] 